#pragma once
#include <GLFW/glfw3.h>

#define CLOSE_APPLICATION GLFW_KEY_ESCAPE

#define WALK_FORWARDS GLFW_KEY_W
#define WALK_BACKWARDS GLFW_KEY_S
#define WALK_RIGHT GLFW_KEY_D
#define WALK_LEFT GLFW_KEY_A

#define JUMP GLFW_KEY_SPACE
#define CROUCH GLFW_KEY_LEFT_SHIFT

#define TOGGLE_DEBUG_MENU GLFW_KEY_F1